build: 
  version: 11.0
  name: 'prod profile v2'


management:
  endpoints:
    web:
      exposure:
        include:
        - info
        - refresh
        - health

encrypt:
  key: qqFlAmCyl2SVIj0B0TpKZo5ErOYVURO0
